version: "3.8"

services:
  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_DB: authdb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: yourpassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    # depends_on:
    #   - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: docker.host.internal
      DB_PORT: 5432
      DB_NAME: authdb
      DB_USER: track_next
      DB_PASSWORD: "Tr@ckNext#2024"
      JWT_SECRET: "@authdb#2025"
      NODE_ENV: dev
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
