module.exports = {
  VALIDATION: {
    INVALID_USERNAME: "ERR_USERNAME_INVALID",
    INVALID_EMAIL: "ERR_EMAIL_INVALID",
    INVALID_PASSWORD: "ERR_PASSWORD_INVALID",
    REQUIRED_USERNAME: "ERR_USERNAME_REQUIRED",
    REQUIRED_PASSWORD: "ERR_PASSWORD_REQUIRED",
    GENERAL: "ERR_VALIDATION_FAILED",
  },
  AUTH: {
    USER_NOT_FOUND: "ERR_USER_NOT_FOUND",
    INVALID_CREDENTIALS: "ERR_INVALID_CREDENTIALS",
    UNAUTHORIZED: "ERR_UNAUTHORIZED",
    INVALID_TOKEN: "ERR_INVALID_TOKEN",
  },
  DB: {
    DUPLICATE_USERNAME: "ERR_DUPLICATE_USERNAME",
    DUPLICATE_EMAIL: "ERR_DUPLICATE_EMAIL",
  },
  SERVER: {
    INTERNAL_SERVER: "ERR_INTERNAL_SERVER",
  },
};
